Update to 2025 from upstream (#1)
* luci: fix dns when default node is direct

* luci: update default config

* luci: update and fix the subscribe module

* luci: direct DNS multiple server

* luci: sing-box 1.8.0 Migrate cache file options

* Migrate cache file from Clash API to independent options

* Not compatible with the sing-box old version, please update to version 1.8.0 or higher.

* luci: Xray 1.8.6 config optimization

* luci: delete the logical code that is not used

* luci: 1.23

* luci: fix #444

* luci: Xray shunt rule DNS in order

* luci: sing-box do not use pre-release

* luci: 1.23-2

* luci: fix hysteria(2) subscribe

* luci: optimization

* luci: 1.24

* luci: fix URI Scheme bug

* luci: optimization

* luci: 1.25

* luci: fix known bugs

* luci: fix hysteria2 share link

* luci: update UoT depends

* luci: fix some subscription links

* luci: add sing-box Shadowsocks SIP003 plugin support

* luci: set Xray DNS nonIPQuery = drop

Xray DNS only basic IP queries (A and AAAA records) are supported. We should drop other queried types, otherwise the so-called "DNS leak" may appear.

* luci: add Xray `mptcp` option support

* luci: check_connect use HTTPS

* luci: Add Xray fragment front-end options (#486)

"Some key-value pair configuration items are used to control
outgoing TCP fragments, which can deceive the censorship
system in some cases, such as bypassing SNI blacklists."

-"packets": Supports two slicing methods. "1-3" is TCP's stream
slicing, which is applied to the client's 1st to 3rd time writing data.
 "tlshello" is the TLS handshake packet slice.

-"length": Fragmented packet length (byte)

-"interval": Fragmentation interval (ms)

https://xtls.github.io/config/outbounds/freedom.html#outboundconfigurationobject

* luci: Add Xray Fragment block to outbounds table (#486)

Add fragment section to outbound table.
We can use fragment option by tagging it to the desired
outbound connections.

* luci: Xray Fragment

* luci: 1.26

* luci: update connect_status curl param

* luci: hysteria2 support verify tls pinSHA256

* luci: fix acl config depends

* luci: fix bugs

* luci: bump version

* action: update auto compile
update action-gh-release version
update cache verion
update compile packages code
add diskspace free code

* action: update auto compile code hide useless warnings

* luci: add node http tls depends

* luci: optimize subscribe

When have a node resolve error, to skip the current node instead of error and exit.

* luci: add Sing-Box node `domain_strategy` option

* luci: fix nftables acl rule error in some cases

* luci: bump version

* luci: add Sing-Box node a layer chain proxy logic

Can set it in the node configuration, no need to use shunt mode.

* luci: Xray wireguard kernelMode set false

* luci: add Xray node a layer chain proxy logic

Can set it in the node configuration, no need to use shunt mode.

* luci: add Xray v1.8.8 balancer leastLoad strategy

* luci: 1.27

* luci: WebSocket EarlyData subscribe compatible

* luci: fix Xray server acceptProxyProtocol and Short Id

* luci: fix direct DNS error that may be triggered

* luci: update iface script

* luci: optimize

* action: fixed compile packages error
fixed https://github.com/xiaorouji/openwrt-passwall-packages/issues/146

* luci: update description

* luci: optimise

* luci: add write to IPSet/NFTSet option

* luci: Xray DNS config optimize

* luci: optimise

* luci: add `client_proxy` option

* luci: use `busybox top` command

* Fix process status check failure after installing procps-ng-top.

Signed-off-by: sbwml <admin@cooluc.com>

* luci: update SS subscription node type

* luci: 1.28

* luci: select backend packages instead of depending on them

* luci: select backend packages instead of depending on them

* luci: make the menu depend on the package itself

* luci: drop Brook

Don't want to maintain too many Go application, please use Socks.

* luci: add Xray HttpUpgrade option

* luci: optimise

* luci: optimise

* luci: bump version

* luci: move IPv6 Nat option out of the menu guard

* luci: Optimize subscribe UA

* luci: add node generate QRCode func

* luci: add Socks log

* luci: bump version

* luci: close #529

* luci: fix #531

* luci: Optimize subscribe

* luci: fixed # unexpected counter

fixed # unexpected counter
```
Error: syntax error, unexpected counter
add rule inet fw4 PSW2_ICMP_REDIRECT oif lo meta l4proto counter redirect
                                                         ^^^^^^^

```

* luci: Update hysteria2.lua (#545)

两个数值顺序颠倒

* luci: xray balancer add fallback support

* luci: optimize xray balancer

* luci: xray balancer support fallback to another balancer

* luci: xray balancer strategy add roundRobin & remove leastLoad

* luci: disable fallback for random & roundRobin strategy

* luci: xray shunt optimization & bug fixes

* luci: optimize and improve

* luci: hotplug.d: output restart log as syslog

* As an application layer service, it should not appear on the kernel log

Signed-off-by: sbwml <admin@cooluc.com>

* luci: shunt rules support with `#` as a annotation line

resolve #544

* luci: fix #553

* luci: bump version

* luci: fix fragment typo

* luci: optimize and improve

* luci: Adjust node log option logic

* luci: adapt lastest luci branch

https://github.com/openwrt/luci/commit/a55b601f3747392947cdd9894c2e63f609d0bb4f

* luci: 1.29

* luci: nftables add icmp redirection whitelist

* luci: sing-box add system interface support for wireguard

* luci: add xray splithttp transport support (#617)

* luci: add socks `bind_local` option

When not checked, Please note the firewall INPUT.

* luci: force enable sniffing when using shunt

* luci: optimize xray sniffing setting logic

* luci: controller optimization

* luci: update default_config & uci-defaults

* luci: add 149.112.112.112（Quad9）DNS option

* luci: add 149.112.112.112（Quad9）DNS option

* luci: distinguish between 9.9.9.9 and 149.112.112.112

---------

Co-authored-by: kwyusdmfu <kwyusdmfu@example.com>

* luci: xray balancer optimization

 - random & roundRobin strategy support fallback node. (Xray v1.8.12+)

* luci: auto update rules and subscribe optimization

* luci: code optimization

* luci: optimize the settings of shunt_rules

* luci: fix bug

* luci: add some probe urls for xray balancer

* luci: DoH DNS address support IPv6

* luci: fix app.sh check_depends fail on installing

* luci: fix hysteria link parsing

* luci: user-agent optimization

* luci: nftables fix high CPU usage in specific situations

* luci: 1.30-1

* luci: fixup

* luci: add haproxy `bind_local` option depends

* luci: update Sing-Box shunt domain_suffix logic

* luci: optimization

* Boot function execute in the background, avoid blocking other processes.

* luci: bump version

* luci: fix #620

* luci: adjust fw4 include script

* luci: fix nftables rules will repeated in some cases

* luci: modify the sing-box shunt rule download link

* luci: simplify the node names for xray and sing-box

* luci: fix bugs in trojan import/export and subscribe

* luci: adapt to Xray-SplitHTTP transport subscribe

* luci: add tuic node import/export and subscribe support

* luci: optimize subscribe

* luci: add `direct_dns_query_strategy` option

Xray UDP DNS does not support `queryStrategy`, so only Sing-Box is supported for now.

* luci: shadowsocks node import/export enhancements and optimizations

* luci: haproxy add health check probe URL option

* luci: Separate the passwall2 nftables rule from the fw4 table

1. Firewall4 restart or reload will flush the entire fw4 tables, include the chains and nftset.
2. Passwall2 backs up the chains and nftset to the file on start so that the rules can be restored when firewall4 reload.It may casue some problem in some cases because of the old nftset.
3. Separate the passwall2 nftables rule from the fw4 table to avoid flush nftset when firewall4 restart.
4. Because the changes of rules structure, need restart firewall4 and update rules to clear old rule caches.

* luci: 1.31

* chmod +x app.sh

Script file permissions lost, restore it.

* luci: Xray support `direct_dns_query_strategy`

* luci: Add support for updating geosite using dlc.dat (#639)

Support updating geosite using dlc.dat from v2fly/domain-list-community (requesting an alternative file name).

* Update Auto compile with openwrt sdk.yml (#636)

* luci: No longer generates a default routing rule for xray (#640)

* luci: add timeout:3d when create whitelist ipset

* Iptables: add timeout:3d when create passwall2_global_whitelist/passwall2_global_whitelist6's ipsets

* Nftables: add timeout:3d when create passwall2_global_whitelist/passwall2_global_whitelist6's ipsets

* luci: Allow force app-update

* luci: Xray sniffing add wechat c2c to xray domain excluded

* luci: Xray nonIPQuery blockTypes

* luci: support device interface level acl

* action: update dependence

* luci: Xray noise

* luci: default preproxy fix

* luci: adapt to openwrt official dnsmasq modifiy

* luci: app_update add mips64el architecture

* luci: modify the ECH configuration of sing-box to a PEM format array

* luci: use date as version

* luci: update the depends check code

* luci: optimize utils

* luci: Fix maxIdleTimeout parameter error in Hysteria2 configuration

fix: https://github.com/xiaorouji/openwrt-passwall2/issues/693

* luci: bump version

* luci: fixed known bugs

* luci: add `1-1` option to Xray fragment packet

* luci: Xray XHTTP

* luci: Xray splitHTTP XMUX

* luci: Xray XHTTP splitting

* luci: fix xhttp typo

* luci: SplitHTTP to XHTTP & TCP to RAW

* luci: fixed know bugs

* action: update

* luci: fix Xray Load Balancing

* action: update

* action: update

* luci: optimize subscription user-agent

---------

Co-authored-by: Tianhe Y <10704839+nftbty@users.noreply.github.com>

* luci: subscribe add sing-box domain strategy options

* luci: app_update add passwall2 version check

* luci: optimize passwall2 check update tips

* luci: update the code to retrieve the passwall2 version

* luci: SplitHTTP to XHTTP & TCP to RAW

Co-Authored-By: Pacalini <141402887+Pacalini@users.noreply.github.com>

* luci: bump version

* luci: fix subscribe bugs

* luci: compatibility modify

* action: update

* luci: bump version

* luci: Adjust AC List source interface logic

Adjust the Access Control List Source Interface logic so that it works with source address.

* luci: Xray XHTTP extra

* luci: config & rules for XHTTP extra

Co-authored-by: lwb1978 <lwb1978@qq.com>

* luci: XHTTP stream-one & ws heartbeatPeriod

from: xiaorouji/openwrt-passwall#3542
by: @lwb1978

* luci: add sniff override function prompt

* luci: add subscribe url access method

Feature Request: https://github.com/xiaorouji/openwrt-passwall/issues/3491

* luci: optimize subscribe url access method

* luci: optimize firewall rule code

* luci: add geoip/geosite database parsing (test)

Related issues: https://github.com/xiaorouji/openwrt-passwall/issues/3492

Co-Authored-By: A-BO <86697442+lwb1978@users.noreply.github.com>

* luci: bump to 24.12.05

* action: add v2ray-geoview compile

* luci: fix xray SniffingObject generate (#724)

* luci: optimize and fix

* luci: Fix incomplete import Trojan URL

* luci: bump to 24.12.11

* luci: add ChinaDNS-NG

Use ChinaDNS-NG instead of Dnsmasq to improve performance and stability.

* luci: optimize and fix

* luci: optimize and improve

Instead of modifying the default dnsmasq, copy it and run. Then hijack DNS on demand.

* luci: geoip database parse to ipset/nftset

* action: update

* luci: bump to 24.12.12

* luci: add and optimize missing logic

* luci: fix https://github.com/xiaorouji/openwrt-passwall2/issues/725

* luci: optimize and fix DNS leak

* luci: bump to 24.12.14

* action: update

* luci: improve

* luci: optimize and improve

* luci: add DNS Redirect option

* luci: Fix import error when VLESS subscribe link encryption is empty

* luci: optimize code

* luci: add preproxy option for Xray/Sing-Box node

* luci: update some configuration logic

* luci: bump to 24.12.16

* luci: Xray ws Forbid "host" in headers, read serverName instead

from: https://github.com/XTLS/Xray-core/commit/a2b773135a860f63e990874c551b099dfc888471

* luci: fix variable error

* luci: fix detail

* luci: optimize and improve

* luci: refresh default configuration

* luci: rework auto stop/start/restart option

* luci: optimize and improve

* luci: bump to 24.12.19

* luci: refresh default configuration

* luci: optimize and improve

* luci: bump to 24.12.21

Happy Winter Solstice~

* luci: fix

* luci: adjust

* luci: optimize and improve

* luci: optimize code

* luci: bump to 24.12.22

* luci: fix and compat

* luci: add Sing-Box DNS `client_subnet` option

* luci: fix dnsmasq with procd-ujail

* luci: fix acl rule when source address is empty

* luci: Xray Transport: Remove HTTP

Migrated to XHTTP "stream-one" mode.
https://github.com/XTLS/Xray-core/commit/ae62a0fb526f2faa0aa8b3fbce5a566187059090

* luci: optimize apk version retrieval

* luci: optimize and improve

* luci: bump to 24.12.25 Merry Chrismas!

Jesus Christ loves you very much.

* luci: add some func to api

* luci: update call uci api

* luci: bump to 24.12.26

* luci: add default values when importing trojan link

* luci: optimize node link import

1. When importing links, the core will be selected based on the settings on the "Node Subscribe" page.
2. Fixed the issue where SS links exported from v2rayN could not be imported.

* luci: Fix Import alpn and fp parameter issues

Co-authored-by: zxl hhyccc <45259624+zxlhhyccc@users.noreply.github.com>

* luci: optimize code

* luci: optimize code

* luci: optimize the compatibility of Xray SS node method

* luci: fix Xray FakeDNS

* luci: fix https://github.com/xiaorouji/openwrt-passwall2/issues/750

* luci: bump to 2025.1.1 New Year!

* luci: update copyright date

* luci: optimize code and adjust

* luci: adjust socks config page button

* luci: optimize code

* luci: adjust

* luci: optimize and fix

* luci: fix https://github.com/xiaorouji/openwrt-passwall2/issues/754

---------

Signed-off-by: sbwml <admin@cooluc.com>
Co-authored-by: xiaorouji <60100640+xiaorouji@users.noreply.github.com>
Co-authored-by: zhusir <smallprogram@foxmail.com>
Co-authored-by: 1TuJl <43652659+1TuJl@users.noreply.github.com>
Co-authored-by: bowhorse <160450443+bowhorse@users.noreply.github.com>
Co-authored-by: Ariesly <Ariesly.Mao@hotmail.com>
Co-authored-by: ShanStone <31815718+ShanStone@users.noreply.github.com>
Co-authored-by: 守望 <61259428+swxk521@users.noreply.github.com>
Co-authored-by: Tianhe Y <10704839+nftbty@users.noreply.github.com>
Co-authored-by: Bard <admin@cooluc.com>
Co-authored-by: MoetaYuko <loli@yuko.moe>
Co-authored-by: Henry19960000 <160483143+Henry19960000@users.noreply.github.com>
Co-authored-by: 756yang <72987022+756yang@users.noreply.github.com>
Co-authored-by: owmyfeellings <46664129+owmyfeellings@users.noreply.github.com>
Co-authored-by: shendageasw <maoerpet@gmail.com>
Co-authored-by: kwyusdmfu <kwyusdmfu@example.com>
Co-authored-by: lwb1978 <86697442+lwb1978@users.noreply.github.com>
Co-authored-by: Liangbin Lian <jjm2473@gmail.com>
Co-authored-by: lwb1978 <lwb1978@qq.com>
Co-authored-by: Pacalini <141402887+Pacalini@users.noreply.github.com>
Co-authored-by: lyin <lyin007@gmail.com>
Co-authored-by: mofanxt <90955575+mofanxt@users.noreply.github.com>
Co-authored-by: Jarao <44677306+WROIATE@users.noreply.github.com>
Co-authored-by: mashkouk <55289441+mashkouk@users.noreply.github.com>
Co-authored-by: nftbty <nftbty@gmail.com>
Co-authored-by: xiaorouji <xiaoroujixxoo@gmail.com>
Co-authored-by: zxl hhyccc <45259624+zxlhhyccc@users.noreply.github.com>